name: Publish new version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (1.0.0)'
        required: true
jobs:
  Publish:
    env:
      VERSION: ${{ github.event.inputs.version }}
      DESCRIPTION: ProcessTuner Command Line Interface
    runs-on: ubuntu-latest
    container: mcr.microsoft.com/dotnet/sdk:5.0-alpine
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Tests
        run: pwsh -File ./Run-Tests.ps1
      - name: Versioning
        run: >
          pwsh -Command "New-ModuleManifest 
          -Path .\ProcessTunerCLI.psd1 
          -ModuleVersion '${VERSION}' 
          -Author '${GITHUB_WORKSPACE}' 
          -Description '${DESCRIPTION}'"
      - name: Publish
        run: pwsh -Command 'Publish-Module -Path . -NuGetApiKey ${{ secrets.NuGetApiKey }}'
      - name: Tagging
        run: |
          git config user.name "Automated Publisher"
          git config user.email "${GITHUB_ACTOR}@${GITHUB_WORKSPACE}.${GITHUB_REPOSITORY}"
          git commit -am "Version v${VERSION} published";
          git remote add github "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}.git";
          git tag "v${VERSION}" && git push github -f --follow-tags